sonar.organization=votre-nom-d-organisation-sonar
sonar.projectKey=votre-pseudo-github_mon-premier-pipeline-ci
sonar.projectName=mon-premier-pipeline-ci

sonar.sources=app.py
sonar.tests=test_app.py
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml